version: '2.2'

services:
        mythtv:
                build:
                        context: .
                        dockerfile: Dockerfile
                image: cargot/sparkly-mythtv
                #                name: mythtv
                network_mode: host
                volumes:
                        - ../../dockervolumes/mythtv/db:/db
                ports:
                        - 3310:3310
                        - 3390:3389
                        - 5000:5000/udp
                        - 5002:5002/udp
                        - 5004:5004/udp
                        - 6543-6544:6543-6544
                        - 6760:6760
                        - 65001:65001
                        - 65001:65001/udp
                privileged: true

