smarthome:
  build: smarthome/.
  volumes:
  - /mnt2/RockOn_Configs/config/smarthomeconfig/etc:/usr/local/smarthome/etc
  - /mnt2/RockOn_Configs/config/smarthomeconfig/items:/usr/local/smarthome/items
  - /mnt2/RockOn_Configs/config/smarthomeconfig/logics:/usr/local/smarthome/logics
  - /mnt2/RockOn_Configs/config/smarthomeconfig/scenes:/usr/local/smarthome/scenes
  - /mnt2/RockOn_Configs/config/smarthomeconfig/tools:/usr/local/smarthome/tools
  - /mnt2/RockOn_Configs/config/smarthomeconfig/var:/usr/local/smarthome/var
#  - /mnt2/RockOn_Configs/config/smarthomeconfig/plugins/denon:/usr/local/smarthome/plugins/denon
#  - /dev/ttyUSB:/dev/ttyUSB
  privileged: true
  ports: 
  - "2323:2323"
  - "2424:2424"
  - "2788:2788"  
  links: 
   - "knxd"
   - "owfs"
   - "smartvisu"
  command: /usr/local/bin/run.sh
  restart: always
  
  
knxd:
  build: ./knxd/.
#  ports: 
#  - "4720:4720"
#  - "6720:6720"
#  - "3671/udp:3671/udp"
  net: "host"
  command: knxd -t 65535 -e=0.0.2 -D -T -R -S -i --GroupCache -b ipt:192.168.177.24
  restart: always


owfs:
  build: ./owfs/.
  volumes:
  - /dev/PBM:/dev/PBM
  command: /usr/sbin/owserver -p 0.0.0.0:4304 -uall -uscan --foreground --pbm=/dev/PBM 
#  ports:
#  - "4304:4304"
#  command: /usr/bin/supervisord
  restart: always
  privileged: true


smartvisu_data:
  build: ./smartvisu/.

smartvisu:
  image: richarvey/nginx-php-fpm
  volumes_from:
  - smartvisu_data
  volumes:
  - /mnt2/RockOn_Configs/config/smartvisuconfig/icons:/copy/icons
  - /mnt2/RockOn_Configs/config/smartvisuconfig/lib:/copy/lib
  - /mnt2/RockOn_Configs/config/smartvisuconfig/pages/friedel/:/copy/pages/friedel
  ports: 
  - 8080:80
  command: ["/bin/bash", "-c", "cp -R /copy/* /usr/share/nginx/html/ ;  /start.sh"]