smarthome-ng:
#  build: smarthome-ng/.
  image: henfri/smarthome-ng
  volumes:
  - /mnt2/Dokumente/Hendrik/docker_smarthome/config/smarthomeNGconfig/etc:/usr/local/smarthome/etc
  - /mnt2/Dokumente/Hendrik/docker_smarthome/config/smarthomeNGconfig/items:/usr/local/smarthome/items
  - /mnt2/Dokumente/Hendrik/docker_smarthome/config/smarthomeNGconfig/logics:/usr/local/smarthome/logics
  - /mnt2/Dokumente/Hendrik/docker_smarthome/config/smarthomeNGconfig/scenes:/usr/local/smarthome/scenes
  - /mnt2/Dokumente/Hendrik/docker_smarthome/config/smarthomeNGconfig/tools:/usr/local/smarthome/tools
  - /mnt2/Dokumente/Hendrik/docker_smarthome/config/smarthomeNGconfig/var:/usr/local/smarthome/var
# example for user provided plugin
# uncomment next line
#  - /mnt2/Dokumente/Hendrik/docker_smarthome/config/smarthomeNGconfig/plugins/whatsapp:/usr/local/smarthome/plugins/whatsapp
# example for devide to be passed
#  - /dev/TEAC:/dev/TEAC
  privileged: true
  ports: 
  - "2323:2323"
  - "2424:2424"
  - "2788:2788"  
  - "8383:8383"
  links: 
   - "owfs"
   - "smartvisu"
   - "grafana"
   - "influxdb"
  command: "/usr/local/bin/run.sh"
  restart: always


  
  
knxd:
  image: henfri/knxd
  net: "host"
  command: knxd --error=0 -D -T -R -S -i --GroupCache --no-tunnel-client-queuing -b ipt:192.168.177.24
  restart: always


owfs:
  image: henfri/owfs
  volumes:
  - /dev/PBM:/dev/PBM
  command: /usr/sbin/owserver -p 0.0.0.0:4304 -uall -uscan --foreground --error_level==0 --error_print=1 --pbm=/dev/PBM 
  restart: always
  privileged: true



smartvisu:
  image: richarvey/nginx-php-fpm
  volumes:
  - /mnt2/Dokumente/Hendrik/docker_smarthome/config/smartvisu/:/var/www/html
  ports: 
  - 8080:80
  restart: always
influxdb:
  image: influxdb:latest
  volumes:
  - /mnt2/RockOn_Configs/config/influxdb/:/var/lib/influxdb
  ports: 
  - 8083:8083
  - 8086:8086
  - 8090:8090
  restart: always

grafana:
  image: grafana/grafana:latest
  volumes:
  - /mnt2/RockOn_Configs/config/grafana/:/var/lib/grafana
  ports: 
  - 3000:3000
  restart: always
  links:
  - influxdb