version: '2.2'

services:
  smarthome-ng:
    build:
      context: /Users/carsten/docker/knx/smarthome-ng
      dockerfile: Dockerfile-1.3 
    image: cargot/smarthome-ng:latest
#    depends-on:
#      - kndx
    volumes:
     - /Users/carsten/dockervolumes/shng-configs/etc:/usr/local/smarthome/etc
     - /Users/carsten/dockervolumes/shng-configs/items:/usr/local/smarthome/items
     - /Users/carsten/dockervolumes/shng-configs/logics:/usr/local/smarthome/logics
     - /Users/carsten/dockervolumes/shng-configs/scenes:/usr/local/smarthome/scenes
     - /Users/carsten/dockervolumes/shng-configs/tools:/usr/local/smarthome/tools
     - /Users/carsten/dockervolumes/shng-configs/var:/usr/local/smarthome/var
#   - /dev/ttyUSB1:/dev/ttyUSB1
    privileged: true
    ports: 
      - "2323:2323"
      - "2424:2424"
      - "2788:2788"
      - "8383:8383"
      - "9010:9010"
#    stop_grace_period: 1m
#    network_mode: bridge
    networks:
      - outside
#    command: bash
#    command: "/usr/local/bin/run.sh"
    command: "/usr/local/smarthome/bin/smarthome.py -i"
    restart: always
    stdin_open: true
#    tty: true


networks:
  outside:
    driver: bridge

